// frontend/admin/vue-element/src/core/preferences/components/PreferencesPanel/AppearancePanel.vue
<template>
  <div class="appearance-panel">
    <!-- 主题模式 -->
    <section class="appearance-section">
      <h3 class="section-title">{{ t("preferences.appearance.theme") }}</h3>
      <div class="theme-mode-options">
        <div class="theme-mode-wrapper" @click="updatePreferences({ theme: { mode: 'light' } })">
          <div class="theme-mode-item" :class="{ active: preferences.theme.mode === 'light' }">
            <ElIcon :size="24"><Sunny /></ElIcon>
          </div>
          <span class="theme-mode-label">{{ t("preferences.appearance.lightMode") }}</span>
        </div>
        <div class="theme-mode-wrapper" @click="updatePreferences({ theme: { mode: 'dark' } })">
          <div class="theme-mode-item" :class="{ active: preferences.theme.mode === 'dark' }">
            <ElIcon :size="24"><Moon /></ElIcon>
          </div>
          <span class="theme-mode-label">{{ t("preferences.appearance.darkMode") }}</span>
        </div>
        <div class="theme-mode-wrapper" @click="updatePreferences({ theme: { mode: 'auto' } })">
          <div class="theme-mode-item" :class="{ active: preferences.theme.mode === 'auto' }">
            <ElIcon :size="24"><Monitor /></ElIcon>
          </div>
          <span class="theme-mode-label">{{ t("preferences.appearance.followSystem") }}</span>
        </div>
      </div>
    </section>

    <!-- 深色侧边栏和顶栏 -->
    <section class="appearance-section">
      <div class="preference-item">
        <span>{{ t("preferences.appearance.darkSidebar") }}</span>
        <ElSwitch
          :disabled="preferences.theme.mode !== 'light'"
          :model-value="preferences.theme.semiDarkSidebar"
          @change="
            (val: string | number | boolean) =>
              updatePreferences({ theme: { semiDarkSidebar: val as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.appearance.darkHeader") }}</span>
        <ElSwitch
          :disabled="preferences.theme.mode !== 'light'"
          :model-value="preferences.theme.semiDarkHeader"
          @change="
            (val: string | number | boolean) =>
              updatePreferences({ theme: { semiDarkHeader: val as boolean } })
          "
        />
      </div>
    </section>

    <!-- 内置主题 -->
    <section class="appearance-section">
      <h3 class="section-title">{{ t("preferences.appearance.builtinThemes") }}</h3>
      <div class="builtin-themes-grid">
        <div
          v-for="theme in BUILTIN_THEMES"
          :key="theme.type"
          class="builtin-theme-wrapper"
          @click="handleBuiltinThemeChange(theme.type)"
        >
          <div
            class="builtin-theme-item"
            :class="{ active: preferences.theme.builtinType === theme.type }"
          >
            <div
              class="theme-color-preview"
              :style="{
                backgroundColor: theme.type === 'custom' ? 'transparent' : theme.color,
                border: theme.type === 'custom' ? '1px dashed #666' : 'none',
              }"
            >
              <ElIcon v-if="theme.type === 'custom'" :size="20"><Brush /></ElIcon>
            </div>
          </div>
          <span class="theme-name">{{ t(`preferences.${theme.nameKey}`) }}</span>
        </div>
      </div>
    </section>

    <!-- 圆角 -->
    <section class="appearance-section">
      <h3 class="section-title">{{ t("preferences.appearance.radius") }}</h3>
      <div class="radius-group">
        <div
          v-for="opt in RADIUS_OPTIONS"
          :key="opt.value"
          class="radius-item"
          :class="{ active: preferences.theme.radius === opt.value }"
          @click="updatePreferences({ theme: { radius: opt.value } })"
        >
          {{ opt.label }}
        </div>
      </div>
    </section>

    <!-- 其它 -->
    <section class="appearance-section">
      <h3 class="section-title">{{ t("preferences.appearance.other") }}</h3>
      <div class="preference-item">
        <span>{{ t("preferences.appearance.colorWeakMode") }}</span>
        <ElSwitch
          :model-value="preferences.app.colorWeakMode"
          @change="
            (val: string | number | boolean) =>
              updatePreferences({ app: { colorWeakMode: val as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.appearance.colorGrayMode") }}</span>
        <ElSwitch
          :model-value="preferences.app.colorGrayMode"
          @change="
            (val: string | number | boolean) =>
              updatePreferences({ app: { colorGrayMode: val as boolean } })
          "
        />
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ElSwitch, ElIcon } from "element-plus";
import { Sunny, Moon, Monitor, Brush } from "@element-plus/icons-vue";
import { useI18n } from "@/i18n";
import { preferences, updatePreferences } from "../../index";
import type { BuiltinThemeType } from "../../types";

const { t } = useI18n();

const BUILTIN_THEMES: { nameKey: string; color: string; type: BuiltinThemeType }[] = [
  { nameKey: "appearance.themes.default", color: "#1677ff", type: "default" },
  { nameKey: "appearance.themes.violet", color: "#722ed1", type: "violet" },
  { nameKey: "appearance.themes.pink", color: "#eb2f96", type: "pink" },
  { nameKey: "appearance.themes.yellow", color: "#fadb14", type: "yellow" },
  { nameKey: "appearance.themes.skyBlue", color: "#52c41a", type: "sky-blue" },
  { nameKey: "appearance.themes.green", color: "#13c2c2", type: "green" },
  { nameKey: "appearance.themes.zinc", color: "#595959", type: "zinc" },
  { nameKey: "appearance.themes.deepGreen", color: "#13a8a8", type: "deep-green" },
  { nameKey: "appearance.themes.deepBlue", color: "#1677ff", type: "deep-blue" },
  { nameKey: "appearance.themes.orange", color: "#fa8c16", type: "orange" },
  { nameKey: "appearance.themes.rose", color: "#f5222d", type: "rose" },
  { nameKey: "appearance.themes.neutral", color: "#595959", type: "neutral" },
  { nameKey: "appearance.themes.slate", color: "#54687a", type: "slate" },
  { nameKey: "appearance.themes.gray", color: "#595959", type: "gray" },
  { nameKey: "appearance.themes.red", color: "#e6393b", type: "red" },
  { nameKey: "appearance.themes.stone", color: "#6b6b6b", type: "stone" },
  { nameKey: "appearance.themes.custom", color: "custom", type: "custom" },
];

const RADIUS_OPTIONS = [
  { label: "0", value: "0" },
  { label: "0.25", value: "0.25" },
  { label: "0.5", value: "0.5" },
  { label: "0.75", value: "0.75" },
  { label: "1", value: "1" },
];

function handleBuiltinThemeChange(type: BuiltinThemeType) {
  if (type === "custom") {
    updatePreferences({ theme: { builtinType: "custom" } });
    return;
  }
  const theme = BUILTIN_THEMES.find((item) => item.type === type);
  if (theme) {
    updatePreferences({ theme: { builtinType: type, colorPrimary: theme.color } });
  }
}
</script>

<style scoped lang="scss">
.appearance-panel {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.appearance-section {
  display: flex;
  flex-direction: column;
  gap: 8px;

  .section-title {
    margin: 0 0 8px;
    font-size: 14px;
    font-weight: 600;
    color: var(--el-text-color-primary);
  }
}

.preference-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 4px 0;
  font-size: 13px;
}

.theme-mode-options {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 8px;
}

.theme-mode-wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  cursor: pointer;
}

.theme-mode-item {
  width: 100%;
  height: 64px;
  border-radius: 6px;
  border: 2px solid var(--el-border-color-lighter);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  color: var(--el-text-color-secondary);
  background: var(--el-fill-color-light);

  &:hover {
    border-color: var(--el-color-primary-light-7);
    background: var(--el-color-primary-light-9);
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
    color: var(--el-color-primary);
  }

  &.active {
    border: 2px solid var(--el-color-primary);
    background: var(--el-fill-color-light);
    box-shadow: 0 0 0 1px var(--el-color-primary);
    color: var(--el-color-primary);
  }
}

.theme-mode-label {
  font-size: 12px;
  font-weight: 500;
  color: var(--el-text-color-regular);
  transition: all 0.3s;
  text-align: center;
}

.builtin-themes-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 8px;
}

.builtin-theme-wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  cursor: pointer;
}

.builtin-theme-item {
  width: 100%;
  height: 64px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border: 2px solid var(--el-border-color-lighter);
  border-radius: 6px;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  background: var(--el-fill-color-light);

  &:hover {
    border-color: var(--el-color-primary-light-7);
    background: var(--el-color-primary-light-9);
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
  }

  &.active {
    border: 2px solid var(--el-color-primary);
    background: var(--el-fill-color-light);
    box-shadow: 0 0 0 1px var(--el-color-primary);
  }
}

.theme-color-preview {
  width: 28px;
  height: 28px;
  border-radius: 5px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s;
}

.theme-name {
  font-size: 12px;
  font-weight: 500;
  color: var(--el-text-color-regular);
  text-align: center;
}

.radius-group {
  display: flex;
  gap: 4px;
  background: var(--el-fill-color-light);
  border-radius: 6px;
  padding: 2px;
}

.radius-item {
  flex: 1;
  height: 36px;
  border-radius: 5px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;

  &:hover {
    color: var(--el-color-primary);
  }

  &.active {
    background: var(--el-bg-color);
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    color: var(--el-color-primary);
  }
}
</style>

// frontend/admin/react/src/core/preferences/components/PreferencesPanel/AppearancePanel.tsx
import React from 'react';
import { Radio, Segmented, Switch } from 'antd';
import { BulbOutlined, LaptopOutlined, MoonOutlined, ReloadOutlined } from '@ant-design/icons';
import { usePreferencesStore } from '../../store';
import type { BuiltinThemeType, ThemeModeType } from '../../types';

/** 内置主题色配置 */
const BUILTIN_THEMES: { name: string; color: string; type: BuiltinThemeType }[] = [
  { name: '默认', color: '#1677ff', type: 'default' },
  { name: '紫罗兰', color: '#722ed1', type: 'violet' },
  { name: '樱花粉', color: '#eb2f96', type: 'pink' },
  { name: '柠檬黄', color: '#fadb14', type: 'yellow' },
  { name: '天蓝色', color: '#52c41a', type: 'sky-blue' },
  { name: '浅绿色', color: '#13c2c2', type: 'green' },
  { name: '锌色灰', color: '#595959', type: 'zinc' },
  { name: '深绿色', color: '#13a8a8', type: 'deep-green' },
  { name: '深蓝色', color: '#1677ff', type: 'deep-blue' },
  { name: '橙黄色', color: '#fa8c16', type: 'orange' },
  { name: '玫瑰红', color: '#f5222d', type: 'rose' },
  { name: '中性色', color: '#595959', type: 'neutral' },
  { name: '石板灰', color: '#54687a', type: 'slate' },
  { name: '中灰色', color: '#595959', type: 'gray' },
  { name: '自定义', color: 'custom', type: 'custom' },
];

/** 圆角选项 */
const RADIUS_OPTIONS = [
  { label: '0', value: '0' },
  { label: '0.25', value: '0.25' },
  { label: '0.5', value: '0.5' },
  { label: '0.75', value: '0.75' },
  { label: '1', value: '1' },
];

export const AppearancePanel: React.FC = () => {
  const { preferences, setPreferences } = usePreferencesStore();

  // 主题模式切换
  const handleThemeModeChange = (mode: ThemeModeType) => {
    setPreferences({ theme: { mode } });
  };

  // 内置主题切换
  const handleBuiltinThemeChange = (type: BuiltinThemeType) => {
    const theme = BUILTIN_THEMES.find((t) => t.type === type);
    if (theme) {
      setPreferences({ theme: { builtinType: type, colorPrimary: theme.color } });
    }
  };

  // 圆角切换
  const handleRadiusChange = (radius: string) => {
    setPreferences({ theme: { radius } });
  };

  return (
    <div className="preference-panel">
      {/* 主题模式 */}
      <section className="preference-section">
        <h3 className="section-title">主题</h3>
        <Radio.Group
          value={preferences.theme.mode}
          onChange={(e) => handleThemeModeChange(e.target.value)}
          className="theme-mode-group"
        >
          <div className="theme-mode-options">
            <Radio.Button value="light" className="theme-mode-btn">
              <div className="theme-mode-content">
                <BulbOutlined className="theme-icon" />
                <span>浅色</span>
              </div>
            </Radio.Button>
            <Radio.Button value="dark" className="theme-mode-btn">
              <div className="theme-mode-content">
                <MoonOutlined className="theme-icon" />
                <span>深色</span>
              </div>
            </Radio.Button>
            <Radio.Button value="auto" className="theme-mode-btn">
              <div className="theme-mode-content">
                <LaptopOutlined className="theme-icon" />
                <span>跟随系统</span>
              </div>
            </Radio.Button>
          </div>
        </Radio.Group>
      </section>

      {/* 深色侧边栏和顶栏 */}
      <section className="preference-section">
        <div className="preference-item">
          <span>深色侧边栏</span>
          <Switch
            checked={preferences.theme.semiDarkSidebar}
            onChange={(checked) => setPreferences({ theme: { semiDarkSidebar: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>深色顶栏</span>
          <Switch
            checked={preferences.theme.semiDarkHeader}
            onChange={(checked) => setPreferences({ theme: { semiDarkHeader: checked } })}
          />
        </div>
      </section>

      {/* 内置主题 */}
      <section className="preference-section">
        <h3 className="section-title">内置主题</h3>
        <div className="builtin-themes-grid">
          {BUILTIN_THEMES.map((theme) => (
            <div
              key={theme.type}
              className={`builtin-theme-item ${preferences.theme.builtinType === theme.type ? 'active' : ''}`}
              onClick={() => handleBuiltinThemeChange(theme.type)}
            >
              <div
                className="theme-color-preview"
                style={{
                  backgroundColor: theme.type === 'custom' ? 'transparent' : theme.color,
                  border: theme.type === 'custom' ? '1px dashed #666' : 'none',
                }}
              >
                {theme.type === 'custom' && <ReloadOutlined className="custom-icon" />}
              </div>
              <span className="theme-name">{theme.name}</span>
            </div>
          ))}
        </div>
      </section>

      {/* 圆角 */}
      <section className="preference-section">
        <h3 className="section-title">圆角</h3>
        <Segmented
          options={RADIUS_OPTIONS}
          value={preferences.theme.radius}
          onChange={(value) => handleRadiusChange(value as string)}
          className="radius-segmented"
          block
        />
      </section>

      {/* 其它 */}
      <section className="preference-section">
        <h3 className="section-title">其它</h3>
        <div className="preference-item">
          <span>色弱模式</span>
          <Switch
            checked={preferences.app.colorWeakMode}
            onChange={(checked) => setPreferences({ app: { colorWeakMode: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>灰色模式</span>
          <Switch
            checked={preferences.app.colorGrayMode}
            onChange={(checked) => setPreferences({ app: { colorGrayMode: checked } })}
          />
        </div>
      </section>
    </div>
  );
};
