// frontend/admin/react/src/pages/app/opm/user/detail/index.tsx
import { useState, useMemo } from 'react';
import { Card, Button, Tabs, Popconfirm, App } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useUpdateUser } from '@/api/hooks/user';
import { queryClient } from '@/core';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';
import { TabEnum } from './types';
import BasicInfoPage from './BasicInfoPage';
import ApiLogPage from './ApiLogPage';
import InternalMessagePage from './InternalMessagePage';
import EditPasswordModal from './EditPasswordModal';

/**
 * 用户详情页面
 */
const UserDetail = () => {
  const { t } = useTranslation('user-detail');
  const navigate = useNavigate();
  const { message } = App.useApp();

  const { id } = useParams<{ id: string }>();
  const userId = useMemo(() => {
    const num = Number(id);
    return isNaN(num) ? undefined : num;
  }, [id]);

  const [activeTab, setActiveTab] = useState<string>(TabEnum.BASIC_INFO);
  const [passwordModalOpen, setPasswordModalOpen] = useState(false);

  // 禁用账户
  const banMutation = useUpdateUser({
    onSuccess: () => {
      message.success(t('banSuccess'));
      queryClient.invalidateQueries({ queryKey: ['getUser'] });
    },
    onError: (error: Error) => {
      message.error(error.message || t('banFailed'));
    },
  });

  const handleBanAccount = () => {
    if (userId) {
      banMutation.mutate({ id: userId, values: { status: 'DISABLED' } });
    }
  };

  const goBack = () => {
    navigate('/opm/users');
  };

  return (
    <ContentContainer heightMode="fixed" padding="16px" bottomMargin={0}>
      {/* 顶部操作栏 */}
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: 12,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <Button type="text" icon={<ArrowLeftOutlined />} onClick={goBack} />
          <span style={{ fontSize: 16, fontWeight: 600 }}>
            {t('title', { userId: userId ?? '-' })}
          </span>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <Popconfirm
            title={t('banConfirmTitle')}
            description={t('banConfirmDesc')}
            onConfirm={handleBanAccount}
            okText={t('common:button.ok')}
            cancelText={t('common:button.cancel')}
          >
            <Button danger>{t('button.banAccount')}</Button>
          </Popconfirm>
          <Button type="primary" onClick={() => setPasswordModalOpen(true)}>
            {t('button.editPassword')}
          </Button>
        </div>
      </div>

      {/* Tabs */}
      <Tabs
        activeKey={activeTab}
        onChange={setActiveTab}
        style={{ marginBottom: 0 }}
        items={[
          {
            key: TabEnum.BASIC_INFO,
            label: t('tab.basicInfo'),
          },
          {
            key: TabEnum.API_AUDIT_LOG,
            label: t('tab.apiAuditLog'),
          },
          {
            key: TabEnum.INTERNAL_MESSAGE,
            label: t('tab.internalMessage'),
          },
        ]}
      />

      {/* Tab 内容 */}
      <Card
        style={{ flex: 1, minHeight: 0, overflow: 'auto' }}
        styles={{
          body: {
            padding: activeTab === TabEnum.BASIC_INFO ? 0 : 16,
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            minHeight: 0,
          },
        }}
      >
        {activeTab === TabEnum.BASIC_INFO && <BasicInfoPage userId={userId} />}
        {activeTab === TabEnum.API_AUDIT_LOG && <ApiLogPage userId={userId} />}
        {activeTab === TabEnum.INTERNAL_MESSAGE && <InternalMessagePage userId={userId} />}
      </Card>

      {/* 修改密码弹窗 */}
      <EditPasswordModal
        open={passwordModalOpen}
        userId={userId}
        onClose={() => setPasswordModalOpen(false)}
      />
    </ContentContainer>
  );
};

export default UserDetail;

// frontend/admin/vue-element/src/pages/app/opm/user/detail/index.vue
<template>
  <div class="user-detail-page">
    <!-- 页面头部 -->
    <div class="page-header">
      <div class="header-left">
        <ElButton link @click="goBack">
          <template #icon>
            <ArrowLeft />
          </template>
        </ElButton>
        <span class="page-title">{{ $t("pages.user.detail.title", { userId }) }}</span>
      </div>
      <div class="header-right">
        <ElButton type="danger" @click="handleBanAccount">
          {{ $t("pages.user.button.banAccount") }}
        </ElButton>
        <ElButton type="primary" @click="handleEditPassword">
          {{ $t("pages.user.button.editPassword") }}
        </ElButton>
      </div>
    </div>

    <!-- 标签页 -->
    <div class="page-content">
      <ElTabs v-model="activeTab" class="detail-tabs">
        <ElTabPane :label="$t('pages.user.detail.tab.basicInfo')" :name="TabEnum.BASIC_INFO" />
        <ElTabPane :label="$t('pages.user.detail.tab.apiAuditLog')" :name="TabEnum.API_AUDIT_LOG" />
        <ElTabPane
          :label="$t('pages.user.detail.tab.internalMessage')"
          :name="TabEnum.INTERNAL_MESSAGE"
        />
      </ElTabs>

      <!-- 标签页内容 -->
      <ElCard v-show="activeTab === TabEnum.BASIC_INFO" class="tab-content">
        <BasicInfoPage :user-id="userId" />
      </ElCard>
      <ElCard v-show="activeTab === TabEnum.API_AUDIT_LOG" class="tab-content">
        <ApiLogPage :user-id="userId" />
      </ElCard>
      <ElCard v-show="activeTab === TabEnum.INTERNAL_MESSAGE" class="tab-content">
        <InternalMessagePage :user-id="userId" />
      </ElCard>
    </div>

    <!-- 编辑密码弹窗 -->
    <EditPasswordModal ref="editPasswordModalRef" @success="handlePasswordSuccess" />
  </div>
</template>

<script lang="ts" setup>
import { computed, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ElMessage, ElMessageBox, ElButton, ElTabs, ElTabPane, ElCard } from "element-plus";
import { ArrowLeft } from "@element-plus/icons-vue";
import { $t } from "@/i18n";

import { useUpdateUser } from "@/api/composables";
import { TabEnum } from "@/pages/app/opm/user/detail/types";

import ApiLogPage from "./api-log-page.vue";
import BasicInfoPage from "./basic-info-page.vue";
import EditPasswordModal from "./components/edit-password-modal.vue";
import InternalMessagePage from "./internal-message-page.vue";

const activeTab = ref<TabEnum>(TabEnum.BASIC_INFO);
const route = useRoute();
const router = useRouter();

const userId = computed(() => {
  const id = route.params.id ?? -1;
  return Number(id);
});

const { mutateAsync: updateUser } = useUpdateUser();

const editPasswordModalRef = ref();

/**
 * 返回上一级页面
 */
function goBack() {
  router.push("/opm/users");
}

/**
 * 禁用账户
 */
async function handleBanAccount() {
  try {
    await ElMessageBox.confirm(
      $t("common.text.do_you_want_disable", {
        moduleName: $t("pages.user.moduleName"),
      }),
      $t("common.dialog.confirm"),
      {
        confirmButtonText: $t("common.button.ok"),
        cancelButtonText: $t("common.button.cancel"),
        type: "warning",
      }
    );

    await updateUser({ id: userId.value, values: { status: "DISABLED" } });
    ElMessage.success($t("common.notification.update_status_success"));
  } catch {
    // 用户取消
  }
}

/**
 * 编辑密码
 */
function handleEditPassword() {
  editPasswordModalRef.value?.open({ userId: userId.value });
}

/**
 * 密码修改成功
 */
function handlePasswordSuccess() {
  ElMessage.success($t("common.notification.update_success"));
}
</script>

<style lang="scss" scoped>
.user-detail-page {
  display: flex;
  flex-direction: column;
  height: 100%;
  background-color: var(--el-bg-color);
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 20px;
  border-bottom: 1px solid var(--el-border-color);

  .header-left {
    display: flex;
    align-items: center;
    gap: 10px;

    .page-title {
      font-size: 16px;
      font-weight: 500;
    }
  }

  .header-right {
    display: flex;
    gap: 8px;
  }
}

.page-content {
  flex: 1;
  min-height: 0;
  padding: 16px 20px;
  display: flex;
  flex-direction: column;
  overflow: hidden;

  .detail-tabs {
    flex-shrink: 0;
    margin-bottom: 16px;
  }

  .tab-content {
    flex: 1;
    min-height: 0;
    overflow: hidden;

    :deep(.el-card__body) {
      height: 100%;
      overflow: hidden;
    }
  }
}
</style>
